### ISSUE TITLE
return OS build version and change requiredMinimumOSVersionBuild to an array

### ISSUE THREAD

**Issue by erikng** [erikng/NudgeSwift#42]
@groob mentioned that we can't just look at a single build we want to enforce because of forked builds.

Apple could potentially release one build of 11.3.0 and another build of it later.

We need to do the following:

1. return the OS build
2. change `requiredMinimumOSVersionBuild` to an array
3. update the logic in `fullyUpdated()` to figure all of this out by moving to some new logic that utilizes `equiredMinimumOSVersionBuild`

**Comment by erikng** [comment]
This was a misunderstanding on my part. We only need to care about this with pre-big sur. And This is only going to work with big sur and higher. If we suddenly see the need, we will re-add `requiredMinimumOSVersionBuild`

**Comment by erikng** [comment]
If we need to bring it back, revert this and then add the required logic. https://github.com/erikng/NudgeSwift/commit/4f2aaa5f42c53fcc2ce26cf3b8a60e1467a4f655

**Comment by cstout1** [comment]
Is there no plan to add requiredMinimumOSVersionBuild back permanently as a user-configurable optional key? Apple has a long track record of releasing updates on the same version number and Nudge currently, unless I'm missing something, will not be able to detect that it's out of date and not on the target release (since the version number didn't change).

**Comment by erikng** [comment]
Unless there is a real world example of this, I'm jot going to change it for now (ignoring beta releases)
